enum CoreBeans {
    USER_SERVICE = 'USER_SERVICE',
    USER_WEB_GATEWAY = 'USER_WEB_GATEWAY',
    USER_ENTITY_GATEWAY = 'USER_ENTITY_GATEWAY',
    LOGGER = 'LOGGER',
    PROFILE_SERVICE = 'PROFILE_SERVICE', 
    PROFILE_ENTITY_GATEWAY = 'PROFILE_ENTITY_GATEWAY',
}

export default CoreBeans;